"""empty message

Revision ID: 34f758ca64aa
Revises: be67c09d0103
Create Date: 2025-02-24 21:04:54.037142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f758ca64aa'
down_revision: Union[str, None] = 'be67c09d0103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rs_association_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rs_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rs_id'], ['resource_server.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rs_association_table')
    # ### end Alembic commands ###
