"""empty message

Revision ID: bae8115df12d
Revises: 8ec57ce06c03
Create Date: 2025-02-20 20:37:24.700231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bae8115df12d"
down_revision: Union[str, None] = "8ec57ce06c03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_server",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "RBAC_BY_AS", "RS_CONTROLLED", name="access_control_type_enum"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "client_rs_association_table",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("rs_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rs_id"],
            ["resource_server.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("role", sa.Column("rs_id", sa.Integer(), nullable=False))
    op.drop_constraint("role_client_id_fkey", "role", type_="foreignkey")
    op.create_foreign_key(None, "role", "client", ["rs_id"], ["id"])
    op.drop_column("role", "client_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role",
        sa.Column(
            "client_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "role", type_="foreignkey")
    op.create_foreign_key(
        "role_client_id_fkey", "role", "client", ["client_id"], ["id"]
    )
    op.drop_column("role", "rs_id")
    op.drop_table("client_rs_association_table")
    op.drop_table("resource_server")
    # ### end Alembic commands ###
