"""empty message

Revision ID: be67c09d0103
Revises: bae8115df12d
Create Date: 2025-02-20 21:13:51.041123

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be67c09d0103"
down_revision: Union[str, None] = "bae8115df12d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("role_rs_id_fkey", "role", type_="foreignkey")
    op.create_foreign_key(None, "role", "resource_server", ["rs_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "role", type_="foreignkey")
    op.create_foreign_key(
        "role_rs_id_fkey", "role", "client", ["rs_id"], ["id"]
    )
    # ### end Alembic commands ###
