"""empty message

Revision ID: d51e8a020777
Revises: fb521da33351
Create Date: 2025-06-07 01:42:26.710439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51e8a020777'
down_revision: Union[str, None] = 'fb521da33351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
