x-logging:
  &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/loki/api/v1/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},d{3}) (?P<message>(?s:.*))$$'

services:
  db:
    image: postgres:15
    container_name: backend_service.db
    command: -p 5432
    expose:
      - 5432
    restart: always
    env_file:
      - .env-prod
    networks:
      - backend_service.db.network
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7
    container_name: redis_auth
    command: ["redis-server", "--port", "6379", "--save", "60", "1", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - backend_service.redis.network
    volumes:
      - redis-data:/data

  api:
    container_name: backend_service.api
    env_file:
      - .env-prod
#    build:
#      context: api
#      dockerfile: Dockerfile.webapi
    image: backend_service.api
    command: [ "sh", "/backend-service.api/docker/app.sh" ]
    expose:
      - 8000
    networks:
      - backend_service.db.network
      - backend_service.redis.network
      - backend_service.grafana.network
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    logging: *default-logging

#  db_migration:
#    profiles: [ "migration" ]
#    container_name: backend_service.db_migration
##    image: backend_service
#    build:
#      context: api
#      dockerfile: Dockerfile.webapi
#    restart: on-failure
#    depends_on:
#      postgres:
#        condition: service_healthy
#    networks:
#      - backend_service.db.network
#    env_file:
#      - api/.env-prod
#    volumes:
#      - ./config:/app/config:ro
#      - ./alembic.ini:/app/alembic.ini:ro
#      - ./src/infrastructure/db/migrations:/app/src/infrastructure/db/migrations:ro
#    command: [ "python", "-m", "alembic", "upgrade", "head" ]

#  nginx:
#    image: nginx:latest
#    container_name: nginx_app
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./app/conf.d:/etc/nginx/conf.d
#      - ./certbot/conf:/etc/letsencrypt
#      - ./nginx-logs:/var/log/nginx
#      - ./certbot/www:/var/www/certbot:rw
#      - ./static:/usr/share/nginx/html
#    depends_on:
#      - backend_service.api
#      - backend_service.db
#      - redis
#      - certbot
#    networks:
#      - backend_service.db.network

  grafana:
    profiles: [ "grafana" ]
    image: grafana/grafana:9.5.2
    container_name: backend_service.grafana
    hostname: backend_service.grafana
    restart: unless-stopped
    expose:
      - "3000"
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - backend_service.grafana.network
    volumes:
      - backend_service.grafana.data:/var/lib/grafana:rw
      - ./grafana/provisioning:/etc/grafana/provisioning:rw
      - ./grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - loki
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - VIRTUAL_HOST=backend_service.grafana
      - NETWORK_ACCESS=internal
      - VIRTUAL_PORT=3000
    logging: *default-logging

  loki:
    profiles: [ "grafana" ]
    image: grafana/loki:2.7.3
    container_name: backend_service.loki
    hostname: backend_service.loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml:ro
      - backend_service.loki.data:/tmp/:rw
    command: -config.file=/etc/loki/config.yaml
    restart: unless-stopped
    networks:
      - backend_service.grafana.network
    logging: *default-logging

  vector:
    profiles: [ "grafana" ]
    image: timberio/vector:0.29.1-alpine
    container_name: backend_service.vector
    hostname: backend_service.vector
    restart: unless-stopped
    expose:
      - "8383"
    networks:
      - backend_service.grafana.network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  prometheus:
    profiles: [ "grafana" ]
    image: prom/prometheus:v2.43.0
    container_name: backend_service.prometheus
    hostname: backend_service.prometheus
    ports:
      - "9090:9090"
    networks:
      - backend_service.grafana.network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - loki
    logging: *default-logging

  tempo:
    profiles: [ "grafana" ]
    image: grafana/tempo:2.0.1
    container_name: backend_service.tempo
    hostname: backend_service.tempo
    command: [ "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    ports:
      - "14250:14250"
    networks:
      - backend_service.grafana.network
    depends_on:
      - loki
    logging: *default-logging

  #  certbot:
#    image: certbot/certbot:latest
#    container_name: certbot
#    volumes:
#      - ./certbot/www:/var/www/certbot:rw
#      - ./certbot/conf:/etc/letsencrypt:rw
#    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $!; done'
#    networks:
#      - custom

#  investments_service:
#    env_file:
#      - investments_src/.env-prod
#    build:
#      context: ./investments_src
#      dockerfile: Dockerfile
#    container_name: investments_service
#    networks:
#      - custom
#    command: ["/bin/sh", "-c", "while true; do make collect-data; sleep 3600; done"]
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # Порт для S3-совместимого API
      - "9001:9001"  # Порт для веб-консоли MinIO
    environment:
      MINIO_ROOT_USER: minio-key  # Замените на ключ доступа длиной от 3 символов
      MINIO_ROOT_PASSWORD: 17471747  # Замените на секретный ключ длиной от 8 символов
    volumes:
      - ./minio-data:/data  # Папка для хранения данных
      - ./minio-config:/root/.minio  # Папка для конфигурационных файлов
    command: server /data --console-address ":9001"
    restart: always

  mc:
    image: minio/mc
    depends_on:
      - minio
    environment:
      - MINIO_ALIAS=myminio
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minio-key
      - MINIO_SECRET_KEY=17471747
      - BUCKET_NAME=users
      - POLICY_NAME=dodiq
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set $${MINIO_ALIAS} $${MINIO_URL} $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      mc mb $${MINIO_ALIAS}/$${BUCKET_NAME} || true;
      mc policy set private $${MINIO_ALIAS}/$${POLICY_NAME}
      "

networks:
    backend_service.db.network: {}
    backend_service.redis.network: {}
    backend_service.grafana.network: {}

volumes:
  db-data:
  redis-data:
  backend_service.grafana.data: {}
  backend_service.loki.data: {}
