services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
    restart: always
    env_file:
      - api/.env-prod
    networks:
      - custom
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_auth
    command: --port 6379
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - custom

  fastapi_app:
    env_file:
      - api/.env-prod
#    build:
#      context: api/
    image: menoitami/auth_service:latest
    command: [ "/fastapi_app/docker/app.sh" ]
    expose:
      - 8000
    networks:
      - custom
    depends_on:
      - db
  nginx:
    image: nginx:latest
    container_name: nginx_app
    ports:
      - "80:80"  # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/conf.d:/etc/nginx/conf.d
      - ./nginx-logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:rw  # Убедитесь, что это rw
    depends_on:
      - fastapi_app
      - db
      - redis
      - certbot  # Зависимость от certbot
    networks:
      - custom

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw  # Убедитесь, что это rw
    networks:
      - custom

networks:
  custom:
    driver: bridge

volumes:
  db-data:
