name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image api service
        run: |
          cd ./auth-service/auth_service && docker build -t backend_service.api:latest --no-cache . && docker tag backend_service.api:latest menoitami/backend_service.api:latest

      - name: Push Docker image api service to Docker Hub
        run: |
          docker push menoitami/backend_service.api:latest

      - name: Build notification service
        run: |
          cd ./auth-service/notification && docker build -t backend_service.notification_app --no-cache . && docker tag backend_service.notification_app:latest menoitami/backend_service.notification_app:latest
      
      - name: Push notification_service
        run: |
          docker push menoitami/backend_service.notification_app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd OpenID-provider/auth-service/
            git pull origin main
            docker compose down
            docker compose pull
            docker compose build --no-cache
            docker compose up -d --force-recreate
            docker compose logs -f | head -n 50  # Вывод первых 50 строк логов