name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -f ./Server/deployment/Dockerfile -t menoitami/mushenger-server:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push menoitami/mushenger-server:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        env:
          HOST: "90.156.170.155"
          USER: "root"
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd rep
            docker-compose down
            git pull
            docker-compose up --build -d
          EOF
